import { imageKitBlurLoader, imageKitLoader } from "@/lib/imageKitLoader";

const photos = [
  {
    id: 1,
    src: "heroImage/hero-image.jpg",
    width: 1080,
    height: 728,
    alt: "Hiking boots",
  },
  {
    id: 2,
    src: "heroImage/hero-image2.jpg",
    width: 1080,
    height: 820,
    alt: "Purple petaled flowers near a mountain",
  },
  {
    id: 3,
    src: "heroImage/hero-image3.jpg",
    width: 1080,
    height: 1620,
    alt: "A person pointing at a beige map",
  },
  {
    id: 4,
    src: "heroImage/hero-image4.jpg",
    width: 1080,
    height: 632,
    alt: "Two hikers walking toward a snow-covered mountain",
  },
  {
    id: 5,
    src: "heroImage/hero-image5.jpg",
    width: 1080,
    height: 1620,
    alt: "A silver and black coffee mug on a brown wooden table",
  },
  {
    id: 6,
    src: "heroImage/hero-image7.jpg",
    width: 1080,
    height: 640,
    alt: "A worm's eye view of trees at night",
  },
  {
    id: 7,
    src: "heroImage/hero-image8.jpg",
    width: 1080,
    height: 800,
    alt: "A pine tree forest near a mountain at sunset",
  },
  {
    id: 8,
    src: "heroImage/hero-image11.jpg",
    width: 1080,
    height: 740,
    alt: "Silhouette photo of three hikers near tall trees",
  },
  {
    id: 9,
    src: "heroImage/hero-image10.jpg",
    width: 1080,
    height: 1400,
    alt: "A person sitting near a bonfire surrounded by trees",
  },
  {
    id: 10,
    src: "heroImage/hero-image6.jpg",
    width: 1080,
    height: 440,
    alt: "Green moss on gray rocks in a river",
  },
  {
    id: 11,
    src: "heroImage/hero-image9.jpg",
    width: 1080,
    height: 1400,
    alt: "Landscape photography of mountains",
  },
  {
    id: 12,
    src: "heroImage/hero-image12.jpg",
    width: 1080,
    height: 560,
    alt: "A pathway between green trees during daytime",
  },
  {
    id: 13,
    src: "heroImage/hero-image13.jpg",
    width: 1080,
    height: 720,
    alt: "A man wearing a black jacket and backpack standing on a grass field during sunset",
  },
  {
    id: 14,
    src: "heroImage/hero-image14.jpg",
    width: 1080,
    height: 480,
    alt: "Green pine trees under white clouds during the daytime",
  },
  {
    id: 15,
    src: "heroImage/hero-image15.jpg",
    width: 1080,
    height: 1620,
    alt: "A hiker sitting near the cliff",
  },
  {
    id: 16,
    src: "heroImage/hero-image16.jpg",
    width: 1080,
    height: 980,
    alt: "A tall mountain with a waterfall running down its side",
  },
].map(({ id, src, alt, width, height }) => ({
  id,
  src: imageKitLoader({ src, width }),
  alt,
  width,
  height,
  blurDataURL: imageKitBlurLoader({ src }),
}));

export default photos;
